module.exports = {
    content: ["./index.html","./src/**/*.{vue,js,ts,jsx,tsx}"],
    safelist: [
      'bg-purple-400',
      'bg-orange-400',
      'bg-blue-400',
      'bg-green-400',
      'bg-blue-500',
      'bg-info',
      'bg-success',
      'bg-warning',
      'bg-error',
      'badge-info',
      'badge-success',    
      'badge-warning',
      'badge-error',
      'radio-info',
      'radio-success',
      'radio-warning',
      'radio-error',
      'tooltip-info',
      'tooltip-success',
      'tooltip-warning',
      'tooltip-error',
      'alert-info',
      'alert-success',
      'alert-warning',
      'alert-error'
    ],      
    plugins: [require("daisyui")],
}